all_states = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
]


crops = ['Amaranthus',
 'Amphophalus',
 'Apple',
 'Arhar (Tur/Red Gram)(Whole)',
 'Ashgourd',
 'Banana',
 'Banana - Green',
 'Beetroot',
 'Bhindi(Ladies Finger)',
 'Bitter gourd',
 'Black pepper',
 'Bottle gourd',
 'Brinjal',
 'Cabbage',
 'Capsicum',
 'Carrot',
 'Cauliflower',
 'Chikoos(Sapota)',
 'Cluster beans',
 'Colacasia',
 'Coriander(Leaves)',
 'Cowpea(Veg)',
 'Cucumbar(Kheera)',
 'Drumstick',
 'Dry Chillies',
 'Elephant Yam (Suran)',
 'Field Pea',
 'French Beans (Frasbean)',
 'Garlic',
 'Ginger(Dry)',
 'Ginger(Green)',
 'Grapes',
 'Green Chilli',
 'Green Peas',
 'Guar',
 'Guava',
 'Gur(Jaggery)',
 'Karbuja(Musk Melon)',
 'Lemon',
 'Lime',
 'Litchi',
 'Maize',
 'Mango',
 'Mango (Raw-Ripe)',
 'Mousambi(Sweet Lime)',
 'Onion',
 'Paddy(Dhan)(Common)',
 'Papaya',
 'Peach',
 'Pear(Marasebu)',
 'Peas Wet',
 'Peas cod',
 'Pineapple',
 'Plum',
 'Pointed gourd (Parval)',
 'Pomegranate',
 'Potato',
 'Pumpkin',
 'Raddish',
 'Rice',
 'Ridgeguard(Tori)',
 'Snakeguard',
 'Soyabean',
 'Spinach',
 'Sponge gourd',
 'Sweet Pumpkin',
 'Tender Coconut',
 'Tinda',
 'Tomato',
 'Water Melon',
 'Wheat',
 'Yam',
 'Yam (Ratalu)']

